<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>                                         
<body>
 
<form action="come.php" method="post">
UserName:<br>
<input type="text" name="username"> <br>

Pessword:<br>
<input type="text" name="password"> <br>

<input type="submit" name="login" value="loig in"> <br>

</form>

</body>
</html>